### PR TITLE
parse all edge cases of ints and floats

### LINKED ISSUE #222: Hexadecimal values or `.inf` fails to get parsed
Yaml values such as `0xFFFF` or `-.inf` are recognized as `Integer` and `Double` but parsing fails:

```scala
scala> println("0xFFFF".as[Int])
Left(ConstructError(Cannot parse 0xFFFF as Int
at 0:0, expected Int
0xFFFF
^ ))

scala> println("-.inf".as[Double])
Left(ConstructError(Cannot parse -.inf as Double
at 0:0, expected Double
-.inf
^ ))
```

### PR DESCRIPTION
**Pull request by lbialy**
closes #222

### CODE REVIEW

File: core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala [hunk 1]
```diff
@@ -85,27 +85,66 @@ object YamlDecoder extends YamlDecoderCompanionCrossCompat {
...
   implicit def forLong: YamlDecoder[Long] = YamlDecoder { case s @ ScalarNode(value, _) =>
-    Try(java.lang.Long.decode(value.replaceAll("_", "")).toLong).toEither.left
+    val normalizedValue =
+      if (value.startsWith("0o")) value.stripPrefix("0o").prepended('0') else value
+
+    Try(java.lang.Long.decode(normalizedValue.replaceAll("_", "")).toLong).toEither.left
       .map(ConstructError.from(_, "Long", s))
   }
 
+  private val infinityRegex = """([-+]?)(\.inf|\.Inf|\.INF)""".r
```
Comment (tgodzik) [inline core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala:103]: Do we need a regex? toLowerCase.endsWith etc. wouldn't be enough here?

Comment (lbialy) [reply core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala:103]: according to spec `.INf` is not a valid`Infinity` :[

also it would be something like:
```scala
if value.nonEmpty then
  if value(0) == '-' then
    if value(1) == '.' then
      if value(2) == 'i' || value(2) == 'I' ...
 ```
which is basically the same thing as what regex would do.

Comment (tgodzik) [reply core/shared/src/main/scala/org/virtuslab/yaml/YamlDecoder.scala:103]: Ok sure, that was just a nitpick

**Review by tgodzik — APPROVED** [review]
